version: '3'
services:

  ld-r:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOWNLOAD_TIMEOUT=10
    volumes:
      - ./logs:/var/log/ld-r
    ports:
      - 8080:4000



